### ISSUE TITLE
Text isn't spoilerized when viewed as an inline reply to a post

### ISSUE THREAD

**Issue by balajisivaraman** [discourse/discourse-spoiler-alert#11]
I hope the title makes sense.

If I reply to an existing post, and it contains spoilers, the actual post is rendered correctly, with the text inside spoiler tags being hidden properly.

However, if you open the reply to the original post by clicking on the 1 Reply link below it, the inline reply reveals everything. There is no spoilerized text in that.

Example in my forum: http://forum.bestpicturesnubs.com/t/the-last-movie-you-watched-0-1/56/41?u=balaji (Warning: Contains revealed spoilers to a film called *The Babadook*.)

**Comment by eviltrout** [comment]
Thanks for letting me know. This is actually a big in discourse which I've fixed in master:

https://github.com/discourse/discourse/commit/b2a74116207bc4da045c351aeab5df8d692e6f53

It should make it into our next release.
