### ISSUE TITLE
Use the details and summary elements

### ISSUE THREAD

**Issue by mark-otaris** [discourse/discourse-spoiler-alert#13]
HTML 5.1 uses [the details element](http://www.w3.org/TR/html51/semantics.html#the-details-element) to represent essentially what this plugin does. The advantages of using it are that it requires no JavaScript code, that it is a semantic element and that it is accessible (screen readers and text browsers can implement mechanisms to make this element work as expected).

Since not all browsers support it yet, it would be a good idea to keep the JavaScript implementation for now.

**Comment by ZogStriP** [comment]
We already support this via the [`discourse-details`](https://github.com/discourse/discourse/tree/master/plugins/discourse-details) plugin. This one is used to blur text/images ;)
