### ISSUE TITLE
Spoiler with img tag broken

### ISSUE THREAD

**Issue by serfma** [discourse/discourse-spoiler-alert#15]
When using a spoiler tag with an image tag, the image tag takes precedence. e.g. [spoiler][img]https://i.imgur.com/bdcDYPw.jpg[/img][/spoiler] 

This causes the image to become blurred, then unblurred and works as a normal image tag.

**Comment by coding-horror** [comment]
Raise this on meta.discourse.org we don't process bugs here

**Comment by serfma** [comment]
My bad, will do!
