### ISSUE TITLE
Plugin breaks Discourse 1.5.3 (stable)

### ISSUE THREAD

**Issue by Narmordil** [discourse/discourse-spoiler-alert#18]
The call:
api.addToolbarPopupMenuOptionsCallback()
in spoiler-alert.js.es6 line 10 throws an error, resulting in a blank page on our Discourse installation, since we upgraded last week (1.5.3, stable branch)

**Comment by eviltrout** [comment]
@tgxworld this looks related to https://github.com/discourse/discourse/commit/5813352439b9b30708f347e7ba2b1c65d5037fda

If we add new api functions we have to bump the API version so that backwards compatibility works and plugins don't fail.

**Comment by tgxworld** [comment]
Opps. Fixed in https://github.com/discourse/discourse-spoiler-alert/commit/cf4f3013a5c6d326d9e565d4a24689d31d362c5f

**Comment by tgxworld** [comment]
Thanks for reporting @Narmordil :smile:
