### ISSUE TITLE
Spoiler content shows in email notifications

### ISSUE THREAD

**Issue by GregoryAveryWeir** [discourse/discourse-spoiler-alert#9]
The email notifications sent out about new posts don't mask the spoiler content. While the styling is probably impossible to do in email, it would be nice to have that text excised from the emails.

**Comment by Swizz540** [comment]
HI,

It should be fixed by the ccd767ed908c426519fd608014254b1dfa4c5efa commit ?

Did you forget to close this issue ?
The result is not relevant yet ?

Thanks for your answer.

Kind regards,

**Comment by GregoryAveryWeir** [comment]
I didn't forget; this issue never got a reply and the fix in question didn't tag the issue, so I had no idea a fix had been made.

Good to see it was fixed!
